pkg install tmux
pkg install nvim
pkg install git
pkg install openssh
pkg install man
pkg install zsh
pkg install fzf
pkg install python
pkg install ripgrep
pkg install htop
pkg install mandoc
pkg install wget
pkg install unzip
pkg install qalc