# Speed
] add speed 0.2
[ add speed -0.2
} add speed 0.4
{ add speed -0.4
/ set speed 1.0

# Seek
SHIFT+LEFT seek -30
SHIFT+RIGHT seek 30

# Chapters
j script-binding select/select-chapter
k add chapter 1
l add chapter -1

# Rebind loop init l
p cycle loop

# Rebind sub init j
h cycle sub
